# description: checks for named equivalent classes, which are not allowed in Mondo

prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entity ?baseLabel ?equivalentClass ?equivalentLabel WHERE 
{
  ?entity owl:equivalentClass ?equivalentClass .
  ?entity rdfs:label ?baseLabel .
  ?equivalentClass rdfs:label ?equivalentLabel .

  FILTER (!isBlank(?entity)) .
  FILTER (!isBlank(?equivalentClass))
}
