PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE {
    ?entity rdfs:subClassOf+ <http://purl.obolibrary.org/obo/MONDO_0000001> .
  	?entity oboInOwl:hasDbXref ?xref .
  	?entity oboInOwl:hasDbXref ?xref2 .
        
    ?xref_anno a owl:Axiom ;
           owl:annotatedSource ?entity ;
           owl:annotatedProperty oboInOwl:hasDbXref ;
           owl:annotatedTarget ?xref ;
           oboInOwl:source ?source1 .
  
  	?xref_anno2 a owl:Axiom ;
           owl:annotatedSource ?entity ;
           owl:annotatedProperty oboInOwl:hasDbXref ;
           owl:annotatedTarget ?xref2 ;
           oboInOwl:source ?source2 .
           
  	FILTER(STRSTARTS(STR(?xref),"DOID") || STRSTARTS(STR(?xref),"Orphanet") || STRSTARTS(STR(?xref),"OMIM") || STRSTARTS(STR(?xref),"GARD"))
    FILTER(str(?xref2)!=str(?xref))
  	FILTER(STRBEFORE(str(?xref),":") = STRBEFORE(str(?xref2),":")) 
  	FILTER NOT EXISTS {
    	?xref_anno oboInOwl:source ?source11 .
      	FILTER ((str(?source11)="MONDO:preferredExternal"))
  	}
    FILTER NOT EXISTS {
    	?xref_anno2 oboInOwl:source ?source21 .
      	FILTER ((str(?source21)="MONDO:preferredExternal"))
  	}
    FILTER ((str(?source1)="MONDO:equivalentTo") || (str(?source1)="MONDO:equivalentObsolete"))
  	FILTER ((str(?source2)="MONDO:equivalentTo") || (str(?source2)="MONDO:equivalentObsolete"))
    FILTER (isIRI(?entity) && STRSTARTS(str(?entity), "http://purl.obolibrary.org/obo/MONDO_"))
    BIND(?xref as ?property)
    BIND(?xref2 as ?value)
}
