prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix IAO: <http://purl.obolibrary.org/obo/IAO_>
prefix RO: <http://purl.obolibrary.org/obo/RO_>
prefix mondo: <http://purl.obolibrary.org/obo/mondo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix dce: <http://purl.org/dc/elements/1.1/>
prefix dc: <http://purl.org/dc/terms/>

SELECT DISTINCT ?term ?property WHERE
{
	?term ?property ?value .
	FILTER (isIRI(?term) && regex(str(?term), "^http://purl.obolibrary.org/obo/MONDO_"))
  	FILTER (?property NOT IN (
		IAO:0000115,
		IAO:0000231,
		IAO:0000233,
		IAO:0000589,
		IAO:0006012,
		IAO:0100001,
		RO:0002161,
		RO:0002175,
		dc:conformsTo,
		dc:creator,
		dce:date,
		mondo:curated_content_resource,
		mondo:excluded_from_qc_check,
		mondo:excluded_subClassOf,
		mondo:excluded_synonym,
		mondo:pathogenesis,
		mondo:related,
		mondo:should_conform_to,
		oboInOwl:consider,
		oboInOwl:creation_date,
		oboInOwl:hasAlternativeId,
		oboInOwl:hasBroadSynonym,
		oboInOwl:hasDbXref,
		oboInOwl:hasExactSynonym,
		oboInOwl:hasNarrowSynonym,
		oboInOwl:hasRelatedSynonym,
		oboInOwl:id,
		oboInOwl:inSubset,
		owl:deprecated,
		owl:disjointWith,
		owl:equivalentClass,
		rdf:type,
		rdfs:comment,
		rdfs:isDefinedBy,
		rdfs:label,
		rdfs:seeAlso,
		rdfs:subClassOf,
		rdfs:subPropertyOf,
		skos:broadMatch,
		skos:closeMatch,
		skos:exactMatch,
		skos:narrowMatch,
		skos:relatedMatch,
		<https://w3id.org/semapv/vocab/crossSpeciesExactMatch>
		)
	)
}
