prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value 
WHERE {
    ?entity ?property ?entity .
    FILTER ( isIRI(?entity)) 
    BIND("Entity referencing itself in triple!" as ?value)
}
ORDER BY ?entity