prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE {
    ?entity rdfs:subClassOf ?value .
    FILTER NOT EXISTS {
       ?child2 rdfs:subClassOf ?value .
       FILTER (?child2 != ?entity)
    }
    BIND(rdfs:subClassOf AS ?property)
    FILTER (isIRI(?entity) && STRSTARTS(str(?entity), "http://purl.obolibrary.org/obo/MONDO_"))
}
ORDER BY ?entity