PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE {
  {
    SELECT ?entity (UCASE(str(?n1)) AS ?ukey) WHERE {
      ?entity rdfs:label ?n1 .
      FILTER NOT EXISTS { ?entity owl:deprecated ?d1 }
    }
  }
  {
    SELECT ?c2 (UCASE(str(?n2)) AS ?ukey) WHERE {
      ?c2 rdfs:label ?n2 .
      FILTER NOT EXISTS { ?c2 owl:deprecated ?d2 }
    }
  }
  FILTER (?entity != ?c2)
  BIND(owl:deprecated AS ?property)
}
ORDER BY ?entity
