# home: hp
prefix hasDbXref: <http://www.geneontology.org/formats/oboInOwl#hasDbXref>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE 
{
  ?entity hasDbXref: ?value .

  FILTER( regex(STR(?value), " ") || regex(STR(?value), ";") || STR(?value) = ""  )
  BIND(hasDbXref: AS ?property)
}
ORDER BY ?entity