prefix IAO: <http://purl.obolibrary.org/obo/IAO_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

#description: Constructing GARD subset

CONSTRUCT {
  ?cls <http://www.geneontology.org/formats/oboInOwl#inSubset> <http://purl.obolibrary.org/obo/mondo#gard_rare> .
}

WHERE
{
  ?cls a owl:Class .

  { 
    ?cls <http://www.geneontology.org/formats/oboInOwl#hasDbXref> ?xref .
    
    ?a <http://www.w3.org/2002/07/owl#annotatedSource> ?cls .
    ?a <http://www.w3.org/2002/07/owl#annotatedProperty> <http://www.geneontology.org/formats/oboInOwl#hasDbXref> .
    ?a <http://www.w3.org/2002/07/owl#annotatedTarget> ?xref .
    ?a <http://www.geneontology.org/formats/oboInOwl#source> ?source .
  
  }
 
  FILTER (strStarts(?source,"MONDO:equivalent"))
  FILTER (strStarts(?xref,"GARD:"))

  FILTER NOT EXISTS {
    ?cls owl:deprecated "true"^^xsd:boolean
  }
 FILTER( !isBlank(?cls) && STRSTARTS(str(?cls), "http://purl.obolibrary.org/obo/MONDO_"))
}
  