PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX IAO: <http://purl.obolibrary.org/obo/IAO_>
PREFIX OMO: <http://purl.obolibrary.org/obo/OMO_>
PREFIX MONDO: <http://purl.obolibrary.org/obo/MONDO_>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

# description: Checks if a proper obsolesence reason was documented for this class

SELECT ?entity ?synonym ?synonym_property ?xref ?st1 ?st2 WHERE {
  VALUES ?synonym_property {
    oboInOwl:hasExactSynonym
    oboInOwl:hasRelatedSynonym
    oboInOwl:hasBroadSynonym
    oboInOwl:hasNarrowSynonym
    rdfs:label
  }
  ?entity ?synonym_property ?synonym .
  FILTER (isIRI(?entity) && STRSTARTS(str(?entity), "http://purl.obolibrary.org/obo/MONDO_"))

  OPTIONAL {
    ?ax owl:annotatedSource ?entity ;
         owl:annotatedProperty ?synonym_property ;
         owl:annotatedTarget ?synonym ;
         oboInOwl:hasDbXref ?xref .
         OPTIONAL {
          ?ax oboInOwl:hasSynonymType ?st1 .
          }
          OPTIONAL {
            ?ax oboInOwl:hasSynonymType ?st2 .
            FILTER(?st1!=?st2)
        }
  }
  
}