prefix IAO: <http://purl.obolibrary.org/obo/IAO_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?subset ?deprecated (COUNT(DISTINCT ?cls) as ?ct)

WHERE
{
    
  VALUES ?subset { 
    <http://purl.obolibrary.org/obo/mondo#gard_rare> 
    <http://purl.obolibrary.org/obo/mondo#mondo_rare> 
    <http://purl.obolibrary.org/obo/mondo#inferred_rare>
    <http://purl.obolibrary.org/obo/mondo#orphanet_rare>
    <http://purl.obolibrary.org/obo/mondo#nord_rare>
    <http://purl.obolibrary.org/obo/mondo#clingen>
    <http://purl.obolibrary.org/obo/mondo#ordo_disorder>
    <http://purl.obolibrary.org/obo/mondo#ordo_subtype_of_a_disorder>
    <http://purl.obolibrary.org/obo/mondo#ordo_group_of_disorders>
    <http://purl.obolibrary.org/obo/mondo#rare>
    <http://purl.obolibrary.org/obo/mondo#otar>
  }

  ?cls <http://www.geneontology.org/formats/oboInOwl#inSubset> ?subset.

  FILTER NOT EXISTS {
    ?cls owl:deprecated ?deprecated
  }
 
 FILTER( !isBlank(?cls) && STRSTARTS(str(?cls), "http://purl.obolibrary.org/obo/MONDO_"))
 #BIND(CONCAT(CONCAT(CONCAT(REPLACE(STR(?subset), "http://purl.obolibrary.org/obo/mondo#", "", "i"),": (Deprecated: "), STR(?deprecated), ")")) AS ?subset_message)
} 
GROUP BY ?subset ?deprecated