PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Get a count of all non-obsolete 'human disease' classes

SELECT (COUNT(DISTINCT ?class) AS ?countHumanDisease)
WHERE {
  # Find subclasses of MONDO:0000001 'disease'
  ?class rdfs:subClassOf* obo:MONDO_0000001 .

  FILTER NOT EXISTS {
    ?class owl:deprecated "true"^^xsd:boolean
  }

  FILTER (isIRI(?class) && STRSTARTS(str(?class), "http://purl.obolibrary.org/obo/MONDO_"))
}
