PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>


# Count of all non-obsolete MONDO:0000001 'disease' classes

SELECT (COUNT(DISTINCT ?class) AS ?countAllDisease)
WHERE {
  ?class rdfs:subClassOf* obo:MONDO_0000001 .

  FILTER (isIRI(?class) && STRSTARTS(str(?class), "http://purl.obolibrary.org/obo/MONDO_"))
  
  FILTER NOT EXISTS { ?class owl:deprecated true }
}
