PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Count the total number of unique non-obsolete Mondo classes that have a definition

SELECT (COUNT(DISTINCT ?class) AS ?clsDefinitionCount)
WHERE {
  ?class rdfs:subClassOf* obo:MONDO_0000001 .
  ?class obo:IAO_0000115 ?definition .
  
  FILTER NOT EXISTS {
    ?class owl:deprecated "true"^^xsd:boolean
  }

 FILTER (isIRI(?class) && STRSTARTS(str(?class), "http://purl.obolibrary.org/obo/MONDO_"))
}
