PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


# Get count of human genetic diseases

SELECT (COUNT(DISTINCT ?class) AS ?countHumanGeneticDiseases)
WHERE {
  # Find subclasses of MONDO:0003847 'hereditary disease'
  ?class rdfs:subClassOf* obo:MONDO_0003847 .

  # Exclude deprecated terms
  FILTER NOT EXISTS {
    ?class owl:deprecated "true"^^xsd:boolean
  }

  # Ensure the class is a MONDO term
  FILTER (isIRI(?class) && STRSTARTS(str(?class), "http://purl.obolibrary.org/obo/MONDO_"))
}
