prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  ?term1 ?term_label1 ?term2 ?term_label2 ?exact1 
WHERE 
{
    ?term1 oboInOwl:hasExactSynonym ?exact1 ;
		rdfs:label ?term_label1 .
    
  	?term2 oboInOwl:hasExactSynonym ?exact2 ;
		rdfs:label ?term_label2 .
    
    FILTER (STR(?term1) < STR(?term2))
 	FILTER (STR(?exact1) = STR(?exact2))
    FILTER (isIRI(?term1) && STRSTARTS(STR(?term1), "http://purl.obolibrary.org/obo/MONDO_"))
    FILTER (isIRI(?term2) && STRSTARTS(STR(?term2), "http://purl.obolibrary.org/obo/MONDO_"))

}