PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX replaced_by: <http://purl.obolibrary.org/obo/IAO_0100001>

SELECT distinct ?nonHumanDisease ?nonHumanDiseaselabel ?humanDisease ?humanDiseaseLabel WHERE {

	?nonHumanDisease a owl:Class; 
  		rdfs:label ?nonHumanDiseaselabel .
     ?humanDisease  a owl:Class; 
  		rdfs:label ?humanDiseaselabel .
    
    ?nonHumanDisease rdfs:subClassOf <http://purl.obolibrary.org/obo/MONDO_0005583> .
    ?humanDisease rdfs:subClassOf <http://purl.obolibrary.org/obo/MONDO_0000001> .

    ?nonHumanDisease rdfs:subClassOf ?humanDisease .

    FILTER NOT EXISTS {
    	?nonHumanDisease owl:deprecated "true"^^xsd:boolean
  	}
    FILTER NOT EXISTS {
          ?humanDisease owl:deprecated "true"^^xsd:boolean
      }
    FILTER NOT EXISTS {
   		?humanDisease rdfs:subClassOf+ <http://purl.obolibrary.org/obo/MONDO_0005583> .
    }
    FILTER( !isBlank(?nonHumanDisease) && regex(str(?nonHumanDisease), "^http://purl.obolibrary.org/obo/MONDO_"))
	FILTER( !isBlank(?humanDisease) && regex(str(?humanDisease), "^http://purl.obolibrary.org/obo/MONDO_"))
}  

