prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix inSubset: <http://www.geneontology.org/formats/oboInOwl#inSubset>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix mondoSubset: <http://purl.obolibrary.org/obo/mondo#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT  ?cls ?clsLabel ?comment ?seeAlso ?scheduledforobsoletion
WHERE 
{
  ?cls <http://www.geneontology.org/formats/oboInOwl#inSubset> <http://purl.obolibrary.org/obo/mondo#obsoletion_candidate>.
  
  ?cls rdfs:label ?clsLabel .
  
    OPTIONAL {
  	?cls rdfs:comment ?comment
  }
  
  OPTIONAL {
  	?cls rdfs:seeAlso ?seeAlso
  }
  
 ?cls <http://purl.obolibrary.org/obo/IAO_0006012> ?scheduledforobsoletion

  FILTER NOT EXISTS { ?cls owl:deprecated "true"^^xsd:boolean }
}
ORDER BY ?cls