PREFIX oio: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX inSubset: <http://www.geneontology.org/formats/oboInOwl#inSubset>

SELECT DISTINCT ?mondo_id
WHERE {
  ?cls inSubset: <http://purl.obolibrary.org/obo/mondo#omim_susceptibility> .
  
  # Extract MONDO ID from the IRI
  BIND(REPLACE(STR(?cls), "http://purl.obolibrary.org/obo/MONDO_", "MONDO:") AS ?mondo_id)
  
  # Filter to only include MONDO terms
  FILTER(STRSTARTS(STR(?cls), "http://purl.obolibrary.org/obo/MONDO_"))
}
ORDER BY ?mondo_id
