PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?gene WHERE {
  ?gene rdfs:subClassOf+ <http://purl.obolibrary.org/obo/SO_0000704> .
}