PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pattern: <http://purl.obolibrary.org/obo/mondo/patterns/>
SELECT DISTINCT ?entity ?property ?value WHERE {
  ?entity rdfs:label ?label .
  FILTER NOT EXISTS {
	  ?entity <http://purl.org/dc/terms/conformsTo> ?pattern
    FILTER (?pattern IN (pattern:inherited_susceptibility.yaml, pattern:susceptibility_by_gene.yaml) )
  }
  FILTER (isIRI(?entity) && STRSTARTS(str(?entity), "http://purl.obolibrary.org/obo/MONDO_"))
  FILTER(regex(str(?label), "suscep"))
  BIND(<http://purl.org/dc/terms/conformsTo> as ?property)
}
ORDER BY ?entity