PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX replaced_by: <http://purl.obolibrary.org/obo/IAO_0100001>
PREFIX MONDO: <http://purl.obolibrary.org/obo/MONDO_>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

#this query reports when an obsoletion-candidate tag is added to a protected term

SELECT ?entity ?property ?value
WHERE 
  { 

VALUES ?property { <http://purl.obolibrary.org/obo/mondo#obsoletion_candidate> }
?entity <http://www.geneontology.org/formats/oboInOwl#inSubset> ?property.

?entity a owl:Class; 
  		rdfs:label ?value .

?entity <http://www.geneontology.org/formats/oboInOwl#inSubset> <http://purl.obolibrary.org/obo/mondo#obsoletion_protected>.

  FILTER( !isBlank(?entity) && regex(str(?entity), "^http://purl.obolibrary.org/obo/MONDO_"))
}
