prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix obo: <http://purl.obolibrary.org/obo/>

SELECT ?cls ?lbl ?omim  ?orphanet ?doid ?efo ?ncit
{
  ?cls a owl:Class ; 
     rdfs:label ?lbl .
  OPTIONAL {
    ?cls oio:hasDbXref ?omim .
    FILTER regex(str(?omim), "^OMIM:")
  }
  OPTIONAL {
    ?cls oio:hasDbXref ?orphanet .
    FILTER regex(str(?orphanet), "^Orphanet:")
  }
  OPTIONAL {
    ?cls oio:hasDbXref ?doid .
    FILTER regex(str(?doid), "^DOID:")
  }
  OPTIONAL {
    ?cls oio:hasDbXref ?efo .
    FILTER regex(str(?efo), "^EFO:")
  }
  OPTIONAL {
    ?cls oio:hasDbXref ?ncit .
    FILTER regex(str(?ncit), "^NCIT:")
  }
}

