prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
  ?sibClass a owl:Class ;
            owl:disjointWith ?c ;
            rdfs:subClassOf ?p ;
            rdfs:label ?sibLabel
}
WHERE {
 ?c rdfs:subClassOf ?p
 NOT EXISTS { ?c owl:deprecated "true"^^xsd:boolean }
 OPTIONAL {
   ?c rdfs:label ?clabel
   BIND(concat("DISJOINT-SIB-OF ", ?clabel) AS ?sibLabel)
 }
 BIND (UUID() as ?sibClass)
}


