prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?a rdfs:subClassOf ?b .
  ?a rdf:type owl:Class .
  ?b rdf:type owl:Class .
  [ rdf:type owl:Axiom ;
    owl:annotatedSource ?a ;
    owl:annotatedProperty rdfs:subClassOf ;
    owl:annotatedTarget ?b ;
    oboInOwl:source "OWLReasoner:Indirect"
  ]
}
WHERE {
  ?a rdfs:subClassOf ?b .
  ?a rdfs:subClassOf ?z .
  ?z rdfs:subClassOf+ ?b 
}
