prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix NCIT: <http://purl.obolibrary.org/obo/NCIT_>

CONSTRUCT {
  ?c oio:hasDbXref ?curie
}
WHERE {
 ?c NCIT:P207 ?x .
 BIND (concat("UMLS:",?x) AS ?curie)
}


