prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
  ?c a owl:Class ;
     rdfs:subClassOf ?type ;
     rdfs:label ?label
}
WHERE {
 ?c rdfs:subClassOf ?type .
 ?c rdfs:label ?label .
}


