prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?cls ?label ?excluded ?excluded_label
WHERE 
{ 
  ?cls <http://purl.obolibrary.org/obo/mondo#excluded_subClassOf> ?excluded ;
      rdfs:subClassOf* ?excluded ;
      rdfs:label ?label .
  OPTIONAL {
    ?excluded rdfs:label ?excluded_label .
  }
  FILTER (isIRI(?excluded) && regex(str(?excluded), "^http://purl.obolibrary.org/obo/MONDO_"))
  FILTER (isIRI(?cls) && regex(str(?cls), "^http://purl.obolibrary.org/obo/MONDO_"))
} LIMIT 500
