prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?d1 ?d2 WHERE 
{
?d1 owl:equivalentClass [ rdf:type owl:Restriction ;
owl:onProperty <http://purl.obolibrary.org/obo/RO_0004020> ;
owl:someValuesFrom ?gene ] . 
?gene rdfs:subClassOf* <http://purl.obolibrary.org/obo/SO_0001217> .
?d2 owl:equivalentClass [ rdf:type owl:Restriction ;
owl:onProperty <http://purl.obolibrary.org/obo/RO_0004020> ;
owl:someValuesFrom ?gene2 ] . 
?gene2 rdfs:subClassOf* <http://purl.obolibrary.org/obo/SO_0001217> .
FILTER EXISTS { ?d1 rdfs:subClassOf* ?d2 .  }
}
