prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix inSubset: <http://www.geneontology.org/formats/oboInOwl#inSubset>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix mondoSubset: <http://purl.obolibrary.org/obo/mondo#>

SELECT  ?cls ?clsLabel
WHERE 
{
  ?cls inSubset: mondoSubset:obsoletion_candidate ;
       rdfs:label ?clsLabel 
}
ORDER BY ?cls
