prefix omim: <http://identifiers.org/omim/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?c ?p ?xc ?xp {
   ?c rdfs:subClassOf+ ?p .
   ?c skos:exactMatch ?xc .
   ?p skos:exactMatch ?xp .
   STRSTARTS(STR(?xc), STR(omim:))
   STRSTARTS(STR(?xp), STR(omim:))
}
