prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix mondo: <http://purl.obolibrary.org/obo/mondo#>
prefix mondoSparql: <http://purl.obolibrary.org/obo/mondo/sparql/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>


CONSTRUCT {
  ?term mondo:excluded_from_qc_check mondoSparql:excluded-subsumption-is-inferred-violation.sparql ;
  rdf:type owl:Class .
}
WHERE 
{ 
  ?term mondo:excluded_subClassOf ?excluded ;
      rdfs:subClassOf* ?excluded ;
      rdfs:label ?term_label .
  
    FILTER NOT EXISTS {
       ?term mondo:excluded_from_qc_check mondoSparql:excluded-subsumption-is-inferred-violation.sparql .
    }
  
  OPTIONAL {
    ?excluded rdfs:label ?excluded_label .
  }
  
  FILTER (isIRI(?excluded) && regex(str(?excluded), "^http://purl.obolibrary.org/obo/MONDO_"))
  FILTER (isIRI(?term) && regex(str(?term), "^http://purl.obolibrary.org/obo/MONDO_"))
  FILTER( ?term=?excluded)
}
