PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Count the total number of unique non-obsolete Mondo classes that are a hereditary disease

SELECT (COUNT(DISTINCT ?class) AS ?hereditaryClassCount)
WHERE {
  ?class rdfs:subClassOf* obo:MONDO_0003847 .
  
  FILTER NOT EXISTS {
    ?class owl:deprecated "true"^^xsd:boolean
  }

  FILTER (isIRI(?class) && STRSTARTS(str(?class), "http://purl.obolibrary.org/obo/MONDO_"))
}