PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (COUNT(DISTINCT ?subclass) AS ?count)
WHERE {
  ?subclass rdfs:subClassOf* obo:MONDO_0000001 .
  
  FILTER NOT EXISTS {
    ?subclass owl:deprecated "true"^^xsd:boolean
  }
}