name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add obo-scripts to PATH
      run: |
        git clone https://github.com/cmungall/obo-scripts.git ${{ github.workspace }}/tools/obo-scripts
        echo "${{ github.workspace }}/tools/obo-scripts" >> $GITHUB_PATH
      shell: bash
      
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Python tools
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install aurelian jinja2-cli "wrapt>=1.17.2"
      shell: bash
      
