# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ issue-2609 ]
  pull_request:
    branches: [ issue-2609 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check some variables
      - name: Print variables
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github)}}
        run: |
          echo "MONDO_BRANCH: ${GITHUB_HEAD_REF}"
          echo "TRAVIS_BRANCH: ${GITHUB_BASE_REF}"
          echo "TRAVIS_COMMIT: ${{ github.event.head_commit.message }}"
          echo "TRAVIS_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}"
          echo "TRAVIS_PULL_REQUEST: ${{ github.event.number }}"
          echo "TRAVIS_PULL_REQUEST_BRANCH: ${BASE_BRANCH}"
          echo "TRAVIS_PULL_REQUEST_SHA: ${GITHUB_SHA}"
          echo "TRAVIS_EVENT_TYPE: ${GITHUB_EVENT_NAME}"
          echo "TRAVIS_BUILD_WEB_URL: https://github.com/monarch-initiative/mondo/runs/${{ github.run_id }}"
          echo "TRAVIS_BUILD_NUMBER: ${{ github.run_number }}"
          echo "$GITHUB_CONTEXT"
        if: github.event_name == 'pull_request'

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

