# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ issue-2609 ]
  pull_request:
    branches: [ issue-2609 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check some variables
      - name: Print variables
        run: |
          echo "current branch $GITHUB_REF"
          echo "Pull request's base branch is: ${BASE_BRANCH}"
          echo "COMMIT sha: ${GITHUB_SHA}"
          env:
            BASE_BRANCH: ${{ github.base_ref }}
          if: github.event_name == 'pull_request'

