name: Update Mappings

on:
#  schedule:
#    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.4.1

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Update DOID mappings
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-doid-mappings -B

      - name: Update ORDO mappings
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-ordo-mappings -B

      - name: Update OMIM mappings
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-omim-mappings -B

      - name: Update NCIT mappings
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-ncit-mappings -B
      
      - name: Update ICD10CM mappings
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-icd10cm-mappings -B
      
      - name: Update ICD10WHO mappings
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-icd10who-mappings -B

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch-suffix: short-commit-hash
          labels: Automated
          body: "Update mappings in Mondo from external sources."
          title: "Weekly automated mappings update"
          base: ${{ github.head_ref }}
          branch: "mapping_automation"
          token: ${{ secrets.GH_TOKEN }}
          reviewers: "sabrinatoro"
