name: Update OMIM Genes References in Mondo

on:
#  schedule:
#    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      
      - name: Update OMIM gene references
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-omim-genes -B
    
      - name: QC
        run: cd src/ontology; make GITHUB_ACTION=true IMP=false PAT=false test -B
        continue-on-error: true  # Allow QC to fail but continue

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch-suffix: short-commit-hash
          labels: automated
          body: "Update OMIM gene references."
          title: "Update OMIM gene references"
          base: ${{ github.head_ref }}
          branch: "omim_gene_references"
          token: ${{ secrets.GH_TOKEN }}
          #reviewers: "sabrinatoro"
