name: Update Synonyms Evidence

on:
#  schedule:
#    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      
      - name: Update Synonyms evidence
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-synonyms-sync -B
    
      - name: QC to ensure that nothing other than provenance has changed
        run: cd src/ontology; make GITHUB_ACTION=true IMP=false PAT=false test -B
        continue-on-error: true  # Allow QC to fail but continue

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch-suffix: short-commit-hash
          labels: automated
          body: "Update the confirmed synonyms axiom annotation."
          title: "Monthly confirmed synonyms evidence update"
          base: ${{ github.head_ref }}
          branch: "confirmed_synonyms_evidence"
          token: ${{ secrets.GH_TOKEN }}
          #reviewers: "sabrinatoro"
